# Generated by Django 4.1 on 2024-09-02 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=400)),
                ('des', models.TextField(max_length=600)),
                ('price', models.TextField(max_length=600)),
                ('sales_price', models.TextField(max_length=600)),
                ('stock', models.CharField(max_length=400)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
                ('cate', models.CharField(blank=True, choices=[('Fruit', 'Fruit'), ('Electronics', 'Electronics'), ('Groccery', 'Groccery'), ('Vegitables', 'Vegitbales')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=600)),
                ('house_no', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=40)),
                ('nearby_landmark', models.CharField(max_length=90)),
                ('phone', models.CharField(max_length=13)),
                ('cart_total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.cartitem')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
