# Generated by Django 4.1 on 2024-09-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cate',
            field=models.CharField(blank=True, choices=[('Groccery', 'Groccery'), ('Fruit', 'Fruit'), ('Electronics', 'Electronics'), ('Vegitables', 'Vegitbales')], max_length=20),
        ),
    ]
